name: Docker Image CI
run-name: Push image to Docker Hub (PR #${{ github.event.number }}) by @${{ github.event.sender.login }}

on:
  pull_request:
    types:
      - closed
    branches: 
      - 'master'

jobs:
  build:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the image 
      run: docker build . --file Dockerfile --tag web-cursos:${{ github.event.number }}
    
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Push image
      run: |
        docker push web-cursos:${{ github.event.number }}
        docker image tag web-cursos:${{ github.event.number }} web-cursos:latest
        docker push web-cursos:latest
        
    - name: Cleanup
      run: |
        docker logout
        docker rmi web-cursos:${{ github.event.number }} web-cursos:latest
        
